version: '3'

services:
  de-risk:
    image: batudal/de-risk-app:0.0.1
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env
  caddy:
    image: batudal/de-risk-caddy:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./volumes/.caddy_data:/data
      - ./volumes/.caddy_config:/config
volumes:
  .caddy_data:
    external: true
  .caddy_config:
