root = "."
tmp_dir = "hmr"

[build]
  args_bin = ["-dev"]
  bin = "./hmr/main"
  cmd = "tailwindcss -i ./public/app.css -o ./public/tw.css --minify && go build -o ./hmr/main . "
  delay = 0
  exclude_dir = ["hmr"]
  exclude_file = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "css"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = true 
  keep_scroll = true
